// plant_descriptions.dart

class PlantProfile {
  final String commonName;
  final String scientificName;
  final String description;
  final String growthHabits;
  final String ecologicalRoles;
  final String uses;

  PlantProfile({
    required this.commonName,
    required this.scientificName,
    required this.description,
    required this.growthHabits,
    required this.ecologicalRoles,
    required this.uses,
  });
}

final Map<String, PlantProfile> plantProfiles = {
  'Zea mays': PlantProfile(
    commonName: 'Maize or Corn',
    scientificName: 'Zea mays',
    description: 'A cereal grain plant first domesticated by indigenous peoples in southern Mexico about 10,000 years ago.',
    growthHabits: 'Annual plant growing up to 3 meters tall with large leaves and ears of grain.',
    ecologicalRoles: 'Supports a variety of wildlife, including insects and birds.',
    uses: 'Consumed as food in various forms, including fresh, processed, and in animal feed.',
  ),
  'Oryza sativa': PlantProfile(
    commonName: 'Rice',
    scientificName: 'Oryza sativa',
    description: 'A staple food crop for a large part of the world, particularly in Asia.',
    growthHabits: 'Grows in flooded fields and requires warm temperatures.',
    ecologicalRoles: 'Important for maintaining wetland ecosystems.',
    uses: 'Primary food source for more than half of the world’s population.',
  ),
  'Hordeum vulgare': PlantProfile(
    commonName: 'Barley',
    scientificName: 'Hordeum vulgare',
    description: 'An ancient cereal grain cultivated since the Bronze Age.',
    growthHabits: 'Annual grass with long, slender stems and grain spikes.',
    ecologicalRoles: 'Often used as cover crop and for soil erosion control.',
    uses: 'Used in food products, animal feed, and for brewing beer.',
  ),
  'Triticum aestivum': PlantProfile(
    commonName: 'Common Wheat',
    scientificName: 'Triticum aestivum',
    description: 'The most widely cultivated species of wheat, used globally for making bread and other products.',
    growthHabits: 'Annual grass with tall, slender stems and dense spikes of grain.',
    ecologicalRoles: 'Supports various wildlife and is crucial for agriculture.',
    uses: 'Main source of flour for bread, pasta, and many other foods.',
  ),
  'Avena sativa': PlantProfile(
    commonName: 'Oats',
    scientificName: 'Avena sativa',
    description: 'A cereal grain known for its nutritional benefits and use in various food products.',
    growthHabits: 'Annual grass with a tall, open structure and loose seed heads.',
    ecologicalRoles: 'Helps improve soil structure and reduce erosion.',
    uses: 'Used in breakfast cereals, oatmeal, and livestock feed.',
  ),
  'Secale cereale': PlantProfile(
    commonName: 'Rye',
    scientificName: 'Secale cereale',
    description: 'A cereal grain closely related to wheat, used in baking and brewing.',
    growthHabits: 'Hardy annual grass with long, narrow leaves and dense seed heads.',
    ecologicalRoles: 'Used as a cover crop to prevent soil erosion and improve soil health.',
    uses: 'Used in bread, rye whiskey, and as animal feed.',
  ),
  'Sorghum bicolor': PlantProfile(
    commonName: 'Sorghum',
    scientificName: 'Sorghum bicolor',
    description: 'A drought-tolerant cereal grain used for food, fodder, and biofuel.',
    growthHabits: 'Tall, robust grass with large seed heads and broad leaves.',
    ecologicalRoles: 'Adapted to arid climates and helps prevent soil erosion.',
    uses: 'Used in foods, beverages, and as animal feed.',
  ),
  'Panicum miliaceum': PlantProfile(
    commonName: 'Proso Millet',
    scientificName: 'Panicum miliaceum',
    description: 'A small-seeded cereal grain cultivated for human consumption and animal feed.',
    growthHabits: 'Annual grass with compact seed heads and slender stems.',
    ecologicalRoles: 'Used in crop rotation systems to enhance soil fertility.',
    uses: 'Used in various foods and as a substitute for rice or wheat.',
  ),
  'Setaria italica': PlantProfile(
    commonName: 'Foxtail Millet',
    scientificName: 'Setaria italica',
    description: 'An ancient cereal grain known for its high nutritional value and adaptability.',
    growthHabits: 'Annual grass with spike-like seed heads and narrow leaves.',
    ecologicalRoles: 'Can be used as a cover crop and for improving soil structure.',
    uses: 'Consumed in various dishes and as a source of animal feed.',
  ),
  'Echinochloa esculenta': PlantProfile(
    commonName: 'Japanese Barnyard Millet',
    scientificName: 'Echinochloa esculenta',
    description: 'A millet variety used for food and animal feed, particularly in Asia.',
    growthHabits: 'Annual grass with dense, erect seed heads and broad leaves.',
    ecologicalRoles: 'Used in traditional agriculture and crop rotations.',
    uses: 'Consumed in various traditional dishes and as animal feed.',
  ),
  'Pennisetum glaucum': PlantProfile(
    commonName: 'Pearl Millet',
    scientificName: 'Pennisetum glaucum',
    description: 'A hardy cereal grain well-suited to dry environments and poor soils.',
    growthHabits: 'Tall, tufted grass with cylindrical seed heads and large leaves.',
    ecologicalRoles: 'Helps improve soil health and is used in arid agriculture.',
    uses: 'Used in foods, traditional beverages, and as fodder.',
  ),
  'Saccharum officinarum': PlantProfile(
    commonName: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    description: 'A tall grass cultivated for its high sugar content and used in sugar production.',
    growthHabits: 'Perennial grass with jointed stems and large, narrow leaves.',
    ecologicalRoles: 'Used in erosion control and soil improvement.',
    uses: 'Primary source of sugar and biofuel, with by-products used in animal feed.',
  ),
   'Cenchrus americanus': PlantProfile(
    commonName: 'American Pennisetum',
    scientificName: 'Cenchrus americanus',
    description: 'A drought-tolerant grass species commonly found in tropical and subtropical regions.',
    growthHabits: 'Forms dense clumps with cylindrical seed heads and fine, narrow leaves.',
    ecologicalRoles: 'Used for soil stabilization and as fodder in arid regions.',
    uses: 'Utilized in pasturelands and for erosion control.',
  ),
  'Cynodon dactylon': PlantProfile(
    commonName: 'Bermudagrass',
    scientificName: 'Cynodon dactylon',
    description: 'A warm-season grass commonly used for lawns, sports fields, and pastures.',
    growthHabits: 'Spreads via underground rhizomes and above-ground stolons, forming a dense turf.',
    ecologicalRoles: 'Helps prevent soil erosion and provides habitat for small wildlife.',
    uses: 'Widely used in landscaping, sports turf, and for erosion control.',
  ),
  'Lolium perenne': PlantProfile(
    commonName: 'Perennial Ryegrass',
    scientificName: 'Lolium perenne',
    description: 'A cool-season grass used for lawns, pastures, and turf.',
    growthHabits: 'Forms dense, lush green turf with fine-textured leaves.',
    ecologicalRoles: 'Improves soil structure and reduces erosion.',
    uses: 'Used in lawn seed mixes, sports fields, and pastures.',
  ),
  'Festuca arundinacea': PlantProfile(
    commonName: 'Tall Fescue',
    scientificName: 'Festuca arundinacea',
    description: 'A robust grass known for its drought tolerance and adaptability to various soil types.',
    growthHabits: 'Forms clumps with broad, dark green leaves and a coarse texture.',
    ecologicalRoles: 'Used for erosion control and in pastures.',
    uses: 'Used in lawns, sports fields, and as forage for livestock.',
  ),
  'Dactylis glomerata': PlantProfile(
    commonName: 'Orchard Grass',
    scientificName: 'Dactylis glomerata',
    description: 'A perennial grass valued for its high forage quality and adaptability.',
    growthHabits: 'Forms dense tufts with broad, flat leaves and loose seed heads.',
    ecologicalRoles: 'Provides high-quality forage and prevents soil erosion.',
    uses: 'Used in pastures, hay production, and for erosion control.',
  ),
  'Phleum pratense': PlantProfile(
    commonName: 'Timothy Grass',
    scientificName: 'Phleum pratense',
    description: 'A grass species often used as forage for livestock, especially horses and rabbits.',
    growthHabits: 'Forms upright tufts with cylindrical seed heads and fine leaves.',
    ecologicalRoles: 'Provides important forage and improves soil structure.',
    uses: 'Used in hay production and as a forage crop.',
  ),
  'Poa pratensis': PlantProfile(
    commonName: 'Kentucky Bluegrass',
    scientificName: 'Poa pratensis',
    description: 'A cool-season grass valued for its lush green appearance and suitability for lawns and sports fields.',
    growthHabits: 'Forms dense, spreading turf with fine-textured leaves.',
    ecologicalRoles: 'Improves soil structure and provides habitat for small wildlife.',
    uses: 'Widely used in lawns, parks, and sports fields.',
  ),
  'Agrostis stolonifera': PlantProfile(
    commonName: 'Creeping Bentgrass',
    scientificName: 'Agrostis stolonifera',
    description: 'A fine-textured grass often used for golf courses and high-maintenance lawns.',
    growthHabits: 'Spreads via stolons, forming a dense, smooth turf.',
    ecologicalRoles: 'Used for erosion control and in high-maintenance landscapes.',
    uses: 'Popular in golf courses, sports fields, and lawn care.',
  ),
  'Bromus inermis': PlantProfile(
    commonName: 'Intermediate Wheatgrass',
    scientificName: 'Bromus inermis',
    description: 'A grass species used for forage and erosion control, known for its adaptability to various conditions.',
    growthHabits: 'Forms dense, bunches with long, narrow leaves and loose seed heads.',
    ecologicalRoles: 'Improves soil health and provides forage for livestock.',
    uses: 'Used in pastures, hay production, and for soil conservation.',
  ),
  'Alopecurus pratensis': PlantProfile(
    commonName: 'Meadow Foxtail',
    scientificName: 'Alopecurus pratensis',
    description: 'A grass species commonly found in meadows and grasslands, valued for its early growth and high forage quality.',
    growthHabits: 'Forms dense tufts with soft, cylindrical seed heads and broad leaves.',
    ecologicalRoles: 'Provides important forage and enhances biodiversity in grasslands.',
    uses: 'Used in hay production and as forage for livestock.',
  ),
    'Deschampsia cespitosa': PlantProfile(
    commonName: 'Tufted Hairgrass',
    scientificName: 'Deschampsia cespitosa',
    description: 'A perennial grass found in meadows and heathlands, known for its dense tufts and fine foliage.',
    growthHabits: 'Forms dense clumps with fine, hair-like leaves and fluffy seed heads.',
    ecologicalRoles: 'Supports a variety of wildlife and helps stabilize soil.',
    uses: 'Used in naturalized landscapes and for soil stabilization.',
  ),
  'Koeleria macrantha': PlantProfile(
    commonName: 'Prairie Junegrass',
    scientificName: 'Koeleria macrantha',
    description: 'A grass species commonly found in prairies and open woodlands, valued for its adaptability and early growth.',
    growthHabits: 'Forms dense, tufted clumps with fine leaves and nodding seed heads.',
    ecologicalRoles: 'Provides forage and improves soil health.',
    uses: 'Used in prairie restorations and as forage for livestock.',
  ),
  'Brachypodium pinnatum': PlantProfile(
    commonName: 'Slender Brome',
    scientificName: 'Brachypodium pinnatum',
    description: 'A perennial grass known for its slender, upright growth and adaptability to various soils.',
    growthHabits: 'Forms loose, open tufts with narrow leaves and delicate seed heads.',
    ecologicalRoles: 'Provides habitat and improves soil structure.',
    uses: 'Used in wildflower meadows and for habitat restoration.',
  ),
  'Arrhenatherum elatius': PlantProfile(
    commonName: 'Tall Oat Grass',
    scientificName: 'Arrhenatherum elatius',
    description: 'A robust grass species valued for its tall, upright growth and adaptability to various soil types.',
    growthHabits: 'Forms tall, dense tufts with broad leaves and large seed heads.',
    ecologicalRoles: 'Provides forage and contributes to soil stability.',
    uses: 'Used in pastureland and as forage for livestock.',
  ),
  'Holcus lanatus': PlantProfile(
    commonName: 'Yorkshire Fog',
    scientificName: 'Holcus lanatus',
    description: 'A grass species commonly found in meadows and pastures, known for its soft, hairy leaves and adaptability.',
    growthHabits: 'Forms dense clumps with soft, woolly leaves and loose seed heads.',
    ecologicalRoles: 'Supports a variety of wildlife and improves soil health.',
    uses: 'Used in pastureland and for erosion control.',
  ),
  'Molinia caerulea': PlantProfile(
    commonName: 'Purple Moor Grass',
    scientificName: 'Molinia caerulea',
    description: 'A perennial grass found in heathlands and wetlands, valued for its tall, flowering stems and dense clumps.',
    growthHabits: 'Forms dense, upright tufts with narrow leaves and tall flower spikes.',
    ecologicalRoles: 'Provides habitat for wildlife and improves soil structure.',
    uses: 'Used in wetland restorations and naturalized landscapes.',
  ),
  'Arundo donax': PlantProfile(
    commonName: 'Giant Reed',
    scientificName: 'Arundo donax',
    description: 'A large, fast-growing grass species often found in riparian zones and wetlands.',
    growthHabits: 'Forms tall, bamboo-like clumps with large, lance-shaped leaves and dense flower spikes.',
    ecologicalRoles: 'Used for erosion control and as a habitat for wildlife.',
    uses: 'Used in bioenergy production and for erosion control.',
  ),
  'Miscanthus giganteus': PlantProfile(
    commonName: 'Giant Miscanthus',
    scientificName: 'Miscanthus giganteus',
    description: 'A perennial grass valued for its high biomass production and use in bioenergy.',
    growthHabits: 'Forms tall, dense clumps with broad, arching leaves and large flower heads.',
    ecologicalRoles: 'Helps in soil conservation and provides bioenergy.',
    uses: 'Used in renewable energy production and for erosion control.',
  ),
  'Phalaris arundinacea': PlantProfile(
    commonName: 'Reed Canarygrass',
    scientificName: 'Phalaris arundinacea',
    description: 'A tall, perennial grass commonly found in wetlands and riparian areas.',
    growthHabits: 'Forms dense stands with tall, upright stems and narrow leaves.',
    ecologicalRoles: 'Provides habitat and helps in soil stabilization.',
    uses: 'Used in wetland restoration and as forage.',
  ),
  'Phragmites australis': PlantProfile(
    commonName: 'Common Reed',
    scientificName: 'Phragmites australis',
    description: 'A widespread wetland grass known for its tall, reed-like stems and dense stands.',
    growthHabits: 'Forms large, dense stands with tall, feathery flower heads and broad leaves.',
    ecologicalRoles: 'Helps in soil stabilization and provides habitat for wildlife.',
    uses: 'Used in wetland restoration and as a natural filtration system.',
  ),
  'Calamagrostis epigejos': PlantProfile(
    commonName: 'Wood Reed',
    scientificName: 'Calamagrostis epigejos',
    description: 'A perennial grass often found in woodlands and grasslands, valued for its dense, spreading growth.',
    growthHabits: 'Forms dense, spreading clumps with narrow leaves and feathery seed heads.',
    ecologicalRoles: 'Provides habitat and helps prevent soil erosion.',
    uses: 'Used in naturalized landscapes and for erosion control.',
  ),
  'Sorghastrum nutans': PlantProfile(
    commonName: 'Yellow Indiangrass',
    scientificName: 'Sorghastrum nutans',
    description: 'A tall, perennial grass native to prairies and open woodlands, known for its golden flower spikes.',
    growthHabits: 'Forms clumps with narrow leaves and tall, feathery flower spikes.',
    ecologicalRoles: 'Supports wildlife and helps in soil stabilization.',
    uses: 'Used in prairie restorations and as forage.',
  ),
'Spartina alterniflora': PlantProfile(
    commonName: 'Smooth Cordgrass',
    scientificName: 'Spartina alterniflora',
    description: 'A salt-tolerant grass commonly found in coastal marshes and estuaries.',
    growthHabits: 'Forms dense stands with long, thin leaves and tall flower spikes.',
    ecologicalRoles: 'Stabilizes marsh sediments and provides habitat for wildlife.',
    uses: 'Used in coastal erosion control and marsh restoration.',
  ),
  'Schizachyrium scoparium': PlantProfile(
    commonName: 'Little Bluestem',
    scientificName: 'Schizachyrium scoparium',
    description: 'A native grass of prairies and open woodlands, known for its attractive blue-green foliage.',
    growthHabits: 'Forms dense clumps with narrow leaves and fluffy seed heads.',
    ecologicalRoles: 'Supports wildlife and improves soil health.',
    uses: 'Used in prairie restorations and as forage for wildlife.',
  ),
  'Andropogon gerardii': PlantProfile(
    commonName: 'Big Bluestem',
    scientificName: 'Andropogon gerardii',
    description: 'A dominant grass species in North American prairies, valued for its tall stature and resilience.',
    growthHabits: 'Forms large, tufted clumps with broad leaves and tall, airy flower heads.',
    ecologicalRoles: 'Provides habitat for wildlife and supports soil health.',
    uses: 'Used in prairie restorations and for livestock forage.',
  ),
  'Bouteloua gracilis': PlantProfile(
    commonName: 'Blue Grama',
    scientificName: 'Bouteloua gracilis',
    description: 'A drought-tolerant grass found in prairies, known for its distinctive seed heads and compact growth.',
    growthHabits: 'Forms dense clumps with narrow leaves and distinctive seed heads resembling eyelashes.',
    ecologicalRoles: 'Provides forage for wildlife and improves soil structure.',
    uses: 'Used in prairie restorations and as forage for livestock.',
  ),
  'Eragrostis tef': PlantProfile(
    commonName: 'Teff',
    scientificName: 'Eragrostis tef',
    description: 'An ancient cereal grain native to Ethiopia, valued for its small seeds and high nutritional value.',
    growthHabits: 'Forms a dense, fine-leafed grass with small seed heads.',
    ecologicalRoles: 'Supports soil health and provides a nutritious food source.',
    uses: 'Used as a staple food in Ethiopia and for animal feed.',
  ),
  'Chloris gayana': PlantProfile(
    commonName: 'Rhodes Grass',
    scientificName: 'Chloris gayana',
    description: 'A perennial grass used for pasture and hay production, known for its rapid growth and adaptability.',
    growthHabits: 'Forms dense tufts with broad leaves and open flower heads.',
    ecologicalRoles: 'Provides forage and helps in soil stabilization.',
    uses: 'Used in pasturelands and for hay production.',
  ),
  'Digitaria sanguinalis': PlantProfile(
    commonName: 'Crabgrass',
    scientificName: 'Digitaria sanguinalis',
    description: 'A common weed grass found in lawns and disturbed areas, known for its aggressive growth.',
    growthHabits: 'Forms low, spreading mats with broad leaves and dense seed heads.',
    ecologicalRoles: 'Often considered invasive, but provides ground cover.',
    uses: 'Usually controlled in managed landscapes and used for forage in some areas.',
  ),
  'Eleusine indica': PlantProfile(
    commonName: 'Goosegrass',
    scientificName: 'Eleusine indica',
    description: 'A tropical grass commonly found in lawns and disturbed areas, known for its fast growth and seed production.',
    growthHabits: 'Forms low, spreading mats with broad leaves and dense seed heads.',
    ecologicalRoles: 'Often considered a weed, but provides ground cover.',
    uses: 'Controlled in managed landscapes and used for forage in some regions.',
  ),
  'Cenchrus ciliaris': PlantProfile(
    commonName: 'Buffelgrass',
    scientificName: 'Cenchrus ciliaris',
    description: 'A drought-tolerant grass native to Africa, valued for its forage quality and erosion control.',
    growthHabits: 'Forms dense clumps with long, narrow leaves and feathery flower heads.',
    ecologicalRoles: 'Used for soil stabilization and as high-quality forage.',
    uses: 'Used in arid regions for pasture and erosion control.',
  ),
  'Bothriochloa ischaemum': PlantProfile(
    commonName: 'King Ranch Bluestem',
    scientificName: 'Bothriochloa ischaemum',
    description: 'A warm-season grass often used for pasture and erosion control, known for its vigorous growth.',
    growthHabits: 'Forms dense, upright clumps with broad leaves and large flower heads.',
    ecologicalRoles: 'Provides forage and improves soil health.',
    uses: 'Used in pasturelands and for erosion control.',
  ),
  'Sporobolus airoides': PlantProfile(
    commonName: ' alkali sacaton',
    scientificName: 'Sporobolus airoides',
    description: 'A perennial grass found in arid and semi-arid regions, known for its drought tolerance and resilience.',
    growthHabits: 'Forms dense, tufted clumps with narrow leaves and delicate flower heads.',
    ecologicalRoles: 'Supports wildlife and helps in soil stabilization.',
    uses: 'Used in rangeland restoration and erosion control.',
  ),
  'Stipa tenuissima': PlantProfile(
    commonName: 'Mexican Feather Grass',
    scientificName: 'Stipa tenuissima',
    description: 'A fine-textured ornamental grass with feathery plumes, native to North and South America.',
    growthHabits: 'Forms dense clumps with thin, arching leaves and delicate flower heads.',
    ecologicalRoles: 'Provides habitat for small wildlife and is used in ornamental landscaping.',
    uses: 'Popular in gardens for its soft texture and graceful appearance.',
  ),
  'Nassella trichotoma': PlantProfile(
    commonName: 'Serrated Tussock',
    scientificName: 'Nassella trichotoma',
    description: 'An invasive grass species that forms dense, serrated clumps, primarily found in Australia and New Zealand.',
    growthHabits: 'Forms large, dense tussocks with serrated leaves and tall flower spikes.',
    ecologicalRoles: 'Considered a weed, it competes with native vegetation.',
    uses: 'Usually controlled in pastures and agricultural lands.',
  ),
  'Aristida purpurea': PlantProfile(
    commonName: 'Purple Three-Awn',
    scientificName: 'Aristida purpurea',
    description: 'A native grass of the western United States, known for its distinctive purple seed heads.',
    growthHabits: 'Forms dense clumps with narrow leaves and tall, airy flower spikes.',
    ecologicalRoles: 'Provides forage for wildlife and helps in soil stabilization.',
    uses: 'Used in native landscaping and prairie restoration.',
  ),
  'Eriochloa villosa': PlantProfile(
    commonName: 'Woolly Cupgrass',
    scientificName: 'Eriochloa villosa',
    description: 'A warm-season annual grass, known for its woolly seed heads, often found in disturbed areas.',
    growthHabits: 'Forms low, spreading mats with broad leaves and woolly seed heads.',
    ecologicalRoles: 'Provides ground cover and is often considered a weed.',
    uses: 'Controlled in agricultural fields and used as forage in some regions.',
  ),
  'Leptochloa dubia': PlantProfile(
    commonName: 'Green Sprangletop',
    scientificName: 'Leptochloa dubia',
    description: 'A warm-season perennial grass used for pasture and erosion control, known for its adaptability to arid conditions.',
    growthHabits: 'Forms dense clumps with narrow leaves and airy flower heads.',
    ecologicalRoles: 'Supports soil health and provides forage for livestock.',
    uses: 'Used in rangeland restoration and as forage in arid regions.',
  ),
  'Cortaderia selloana': PlantProfile(
    commonName: 'Pampas Grass',
    scientificName: 'Cortaderia selloana',
    description: 'A large, ornamental grass native to South America, known for its tall plumes.',
    growthHabits: 'Forms large, dense clumps with tall, feathery flower plumes.',
    ecologicalRoles: 'Used in ornamental landscaping but can be invasive in some regions.',
    uses: 'Popular in gardens for its dramatic appearance, often used as a windbreak.',
  ),
  'Achnatherum hymenoides': PlantProfile(
    commonName: 'Indian Ricegrass',
    scientificName: 'Achnatherum hymenoides',
    description: 'A native grass of the western United States, valued for its nutritious seeds.',
    growthHabits: 'Forms dense clumps with fine leaves and delicate flower heads.',
    ecologicalRoles: 'Provides forage for wildlife and livestock, supports soil health.',
    uses: 'Used in rangeland restoration and as a food source by Native Americans.',
  ),
  'Melica ciliata': PlantProfile(
    commonName: 'Silky Melic Grass',
    scientificName: 'Melica ciliata',
    description: 'A perennial grass native to Europe and Asia, known for its fine texture and silvery flower heads.',
    growthHabits: 'Forms dense clumps with narrow leaves and silky flower heads.',
    ecologicalRoles: 'Provides habitat for wildlife and is used in ornamental landscaping.',
    uses: 'Popular in gardens for its graceful appearance and fine texture.',
  ),
  'Briza media': PlantProfile(
    commonName: 'Quaking Grass',
    scientificName: 'Briza media',
    description: 'A perennial grass native to Europe, known for its distinctive, quaking seed heads.',
    growthHabits: 'Forms dense clumps with narrow leaves and pendulous seed heads.',
    ecologicalRoles: 'Provides ground cover and is used in ornamental landscaping.',
    uses: 'Popular in gardens for its unique seed heads that quiver in the wind.',
  ),
  'Tridens flavus': PlantProfile(
    commonName: 'Purpletop',
    scientificName: 'Tridens flavus',
    description: 'A native grass of North America, known for its purple-tinged seed heads.',
    growthHabits: 'Forms dense clumps with broad leaves and tall, airy flower heads.',
    ecologicalRoles: 'Provides forage for wildlife and helps in soil stabilization.',
    uses: 'Used in prairie restorations and as forage for livestock.',
  ),
  'Paspalum notatum': PlantProfile(
    commonName: 'Bahia Grass',
    scientificName: 'Paspalum notatum',
    description: 'A warm-season perennial grass commonly used for lawns and pastures in the southeastern United States.',
    growthHabits: 'Forms dense, low-growing mats with broad leaves and tall flower spikes.',
    ecologicalRoles: 'Provides ground cover and helps in soil stabilization.',
    uses: 'Popular for lawns, pastures, and erosion control in warm climates.',
  ),
  'Axonopus compressus': PlantProfile(
    commonName: 'Carpet Grass',
    scientificName: 'Axonopus compressus',
    description: 'A low-growing, perennial grass commonly used for lawns and ground cover in tropical regions.',
    growthHabits: 'Forms dense, creeping mats with broad leaves and small, inconspicuous flower spikes.',
    ecologicalRoles: 'Provides ground cover, helps in soil stabilization, and is resistant to foot traffic.',
    uses: 'Popular for lawns, parks, and as ground cover in warm, humid climates.',
  ),
  'Zoysia japonica': PlantProfile(
    commonName: 'Japanese Lawngrass',
    scientificName: 'Zoysia japonica',
    description: 'A warm-season, perennial grass native to Southeast Asia, known for its dense, fine texture.',
    growthHabits: 'Forms dense, slow-growing mats with fine leaves and small, cylindrical flower spikes.',
    ecologicalRoles: 'Provides durable ground cover, supports soil health, and is drought-tolerant.',
    uses: 'Widely used for lawns, sports fields, and golf courses in warm climates.',
  ),
  'Sporobolus cryptandrus': PlantProfile(
    commonName: 'Sand Dropseed',
    scientificName: 'Sporobolus cryptandrus',
    description: 'A native grass of North America, known for its fine texture and ability to grow in sandy soils.',
    growthHabits: 'Forms dense clumps with fine leaves and delicate flower heads.',
    ecologicalRoles: 'Provides ground cover, helps in soil stabilization, and is used in prairie restoration.',
    uses: 'Used in native landscaping, prairie restoration, and erosion control projects.',
  ),
  'Muhlenbergia capillaris': PlantProfile(
    commonName: 'Pink Muhly Grass',
    scientificName: 'Muhlenbergia capillaris',
    description: 'An ornamental grass native to North America, known for its airy, pink flower plumes.',
    growthHabits: 'Forms dense clumps with fine leaves and tall, feathery flower plumes.',
    ecologicalRoles: 'Provides habitat for small wildlife and is used in ornamental landscaping.',
    uses: 'Popular in gardens for its striking, pink flower plumes and graceful appearance.',
  ),
  'Schizachyrium littorale': PlantProfile(
    commonName: 'Dune Bluestem',
    scientificName: 'Schizachyrium littorale',
    description: 'A native grass of the coastal regions of North America, known for its blue-green foliage.',
    growthHabits: 'Forms dense clumps with narrow, blue-green leaves and tall, airy flower heads.',
    ecologicalRoles: 'Helps in dune stabilization and provides habitat for coastal wildlife.',
    uses: 'Used in coastal restoration projects and ornamental landscaping in coastal areas.',
  ),
  'Digitaria didactyla': PlantProfile(
    commonName: 'Blue Couch Grass',
    scientificName: 'Digitaria didactyla',
    description: 'A low-growing, perennial grass commonly used for lawns in tropical regions.',
    growthHabits: 'Forms dense, creeping mats with broad leaves and small, inconspicuous flower spikes.',
    ecologicalRoles: 'Provides durable ground cover, resistant to foot traffic and drought.',
    uses: 'Popular for lawns, parks, and as ground cover in warm, humid climates.',
  ),
  'Miscanthus sinensis': PlantProfile(
    commonName: 'Chinese Silver Grass',
    scientificName: 'Miscanthus sinensis',
    description: 'A tall, ornamental grass native to East Asia, known for its silver plumes and graceful appearance.',
    growthHabits: 'Forms large, dense clumps with narrow leaves and tall, feathery flower plumes.',
    ecologicalRoles: 'Provides habitat for wildlife and is used in ornamental landscaping.',
    uses: 'Popular in gardens and landscapes for its striking appearance and drought tolerance.',
  ),
  'Aristida stricta': PlantProfile(
    commonName: 'Wiregrass',
    scientificName: 'Aristida stricta',
    description: 'A native grass of the southeastern United States, known for its stiff, wire-like leaves.',
    growthHabits: 'Forms dense clumps with narrow, stiff leaves and tall, airy flower heads.',
    ecologicalRoles: 'Helps in soil stabilization and provides habitat for wildlife in pine savannas.',
    uses: 'Used in native landscaping and habitat restoration projects.',
  ),
  'Chasmanthium latifolium': PlantProfile(
    commonName: 'Northern Sea Oats',
    scientificName: 'Chasmanthium latifolium',
    description: 'A native grass of North America, known for its unique, flat seed heads.',
    growthHabits: 'Forms dense clumps with broad leaves and distinctive, flat seed heads that dangle from arching stems.',
    ecologicalRoles: 'Provides habitat for wildlife and is used in ornamental landscaping.',
    uses: 'Popular in gardens for its unique seed heads and ability to thrive in shaded areas.',
  ),
  'Buchloe dactyloides': PlantProfile(
    commonName: 'Buffalograss',
    scientificName: 'Buchloe dactyloides',
    description: 'A warm-season, perennial grass native to the Great Plains of North America, known for its drought tolerance.',
    growthHabits: 'Forms dense, low-growing mats with fine leaves and small, inconspicuous flower spikes.',
    ecologicalRoles: 'Provides durable ground cover, supports soil health, and is drought-tolerant.',
    uses: 'Widely used for lawns, pastures, and erosion control in arid regions.',
  ),
  'Bouteloua curtipendula': PlantProfile(
    commonName: 'Sideoats Grama',
    scientificName: 'Bouteloua curtipendula',
    description: 'A warm-season, perennial grass native to North America, known for its unique, oat-like seed heads.',
    growthHabits: 'Forms dense clumps with narrow leaves and distinctive, arching seed spikes.',
    ecologicalRoles: 'Provides habitat for wildlife, supports pollinators, and is drought-tolerant.',
    uses: 'Used in native landscaping, prairie restoration, and erosion control projects.',
  ),
  'Cymbopogon citratus': PlantProfile(
    commonName: 'Lemongrass',
    scientificName: 'Cymbopogon citratus',
    description: 'A tropical grass known for its lemon-scented leaves, commonly used in cooking and herbal remedies.',
    growthHabits: 'Forms dense clumps with long, narrow leaves and tall, slender flower spikes.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is used in permaculture.',
    uses: 'Popular in culinary uses, herbal medicine, and as a natural insect repellent.',
  ),
  'Imperata cylindrica': PlantProfile(
    commonName: 'Cogongrass',
    scientificName: 'Imperata cylindrica',
    description: 'A highly invasive grass species known for its sharp leaves and aggressive growth habits.',
    growthHabits: 'Forms dense, spreading clumps with narrow, sharp leaves and tall, fluffy flower heads.',
    ecologicalRoles: 'Considered a problematic invasive species that disrupts native ecosystems.',
    uses: 'Used in erosion control and as an ornamental plant, though often discouraged due to its invasiveness.',
  ),
  'Tripsacum dactyloides': PlantProfile(
    commonName: 'Eastern Gamagrass',
    scientificName: 'Tripsacum dactyloides',
    description: 'A warm-season, perennial grass native to North America, known for its tall stature and robust growth.',
    growthHabits: 'Forms large clumps with broad leaves and tall, thick flower spikes.',
    ecologicalRoles: 'Provides forage for livestock, habitat for wildlife, and is used in prairie restoration.',
    uses: 'Used in pastures, native landscaping, and as a forage crop.',
  ),
  'Phragmites karka': PlantProfile(
    commonName: 'Tropical Reed',
    scientificName: 'Phragmites karka',
    description: 'A tall, perennial grass native to tropical regions, known for its robust growth and large, feathery plumes.',
    growthHabits: 'Forms dense stands with tall, hollow stems and large, feathery flower heads.',
    ecologicalRoles: 'Provides habitat for wildlife, helps in wetland restoration, and is used for erosion control.',
    uses: 'Used in wetland restoration, erosion control, and as an ornamental plant.',
  ),
  'Poa annua': PlantProfile(
    commonName: 'Annual Bluegrass',
    scientificName: 'Poa annua',
    description: 'A cool-season, annual grass known for its small size and bright green color.',
    growthHabits: 'Forms small, low-growing clumps with fine leaves and small, greenish flower spikes.',
    ecologicalRoles: 'Commonly found in lawns and gardens, often considered a weed due to its prolific seeding.',
    uses: 'Used in lawns, though often managed as a weed in turfgrass settings.',
  ),
  'Phalaris canariensis': PlantProfile(
    commonName: 'Canary Grass',
    scientificName: 'Phalaris canariensis',
    description: 'A cool-season, annual grass native to the Mediterranean region, known for its seed production.',
    growthHabits: 'Forms dense clumps with broad leaves and large, cylindrical seed heads.',
    ecologicalRoles: 'Grown for its seeds, which are used as bird feed, and also used in ornamental gardens.',
    uses: 'Cultivated primarily for bird seed and as an ornamental grass in gardens.',
  ),
  'Cymbopogon nardus': PlantProfile(
    commonName: 'Citronella Grass',
    scientificName: 'Cymbopogon nardus',
    description: 'A tropical grass known for its strong citronella scent, used as a natural insect repellent.',
    growthHabits: 'Forms dense clumps with long, narrow leaves and tall, slender flower spikes.',
    ecologicalRoles: 'Provides ground cover and is used in permaculture systems.',
    uses: 'Popular for its use in making citronella oil, used in candles and sprays as an insect repellent.',
  ),
  'Sporobolus virginicus': PlantProfile(
    commonName: 'Seashore Dropseed',
    scientificName: 'Sporobolus virginicus',
    description: 'A perennial grass native to coastal regions, known for its salt tolerance and ability to stabilize dunes.',
    growthHabits: 'Forms dense, spreading mats with fine leaves and small, inconspicuous flower spikes.',
    ecologicalRoles: 'Provides habitat for coastal wildlife, helps in dune stabilization, and supports soil health.',
    uses: 'Used in coastal restoration, erosion control, and as a ground cover in saline environments.',
  ),
  'Leersia oryzoides': PlantProfile(
    commonName: 'Rice Cutgrass',
    scientificName: 'Leersia oryzoides',
    description: 'A perennial grass native to North America, known for its sharp, serrated leaves and wetland habitat.',
    growthHabits: 'Forms dense clumps with broad, rough leaves and small, greenish flower spikes.',
    ecologicalRoles: 'Provides habitat for wetland wildlife and helps in water filtration and wetland restoration.',
    uses: 'Used in wetland restoration and as forage for livestock in wet areas.',
  ),
   'Zoysia matrella': PlantProfile(
    commonName: 'Manila Grass',
    scientificName: 'Zoysia matrella',
    description: 'A warm-season, perennial grass known for its fine texture and dense growth, commonly used in lawns and sports fields.',
    growthHabits: 'Forms dense, low-growing mats with fine, dark green leaves and small, inconspicuous flower spikes.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is drought-tolerant.',
    uses: 'Popular for use in lawns, sports fields, and as a ground cover in warm climates.',
  ),
  'Spartina patens': PlantProfile(
    commonName: 'Saltmeadow Cordgrass',
    scientificName: 'Spartina patens',
    description: 'A perennial grass native to coastal regions, known for its salt tolerance and role in stabilizing salt marshes.',
    growthHabits: 'Forms dense, spreading mats with fine, wiry leaves and small, greenish flower spikes.',
    ecologicalRoles: 'Provides habitat for coastal wildlife, supports soil health, and helps in stabilizing salt marshes.',
    uses: 'Used in coastal restoration, erosion control, and as a ground cover in saline environments.',
  ),
  'Paspalum dilatatum': PlantProfile(
    commonName: 'Dallisgrass',
    scientificName: 'Paspalum dilatatum',
    description: 'A warm-season, perennial grass known for its robust growth and tolerance to a variety of soil types.',
    growthHabits: 'Forms dense clumps with broad leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides forage for livestock, supports soil health, and is used in pasture management.',
    uses: 'Used in pastures, hay production, and as a forage crop for livestock.',
  ),
  'Bromus catharticus': PlantProfile(
    commonName: 'Rescuegrass',
    scientificName: 'Bromus catharticus',
    description: 'A cool-season, annual or biennial grass known for its rapid growth and adaptability to various conditions.',
    growthHabits: 'Forms loose clumps with broad leaves and tall, open flower spikes.',
    ecologicalRoles: 'Provides forage for livestock and is often found in disturbed areas such as roadsides and fields.',
    uses: 'Used in pastures, forage production, and soil stabilization projects.',
  ),
  'Lolium multiflorum': PlantProfile(
    commonName: 'Italian Ryegrass',
    scientificName: 'Lolium multiflorum',
    description: 'A cool-season, annual grass known for its fast growth and high-quality forage production.',
    growthHabits: 'Forms dense clumps with narrow leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides high-quality forage for livestock and is used in pasture management.',
    uses: 'Widely used in pasture, hay production, and as a cover crop.',
  ),
  'Festuca ovina': PlantProfile(
    commonName: 'Sheep Fescue',
    scientificName: 'Festuca ovina',
    description: 'A cool-season, perennial grass known for its fine texture and ability to thrive in poor soils.',
    growthHabits: 'Forms dense, low-growing clumps with fine, needle-like leaves and small, greenish flower spikes.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is drought-tolerant.',
    uses: 'Used in low-maintenance lawns, ground cover, and erosion control projects.',
  ),
  'Bromus hordeaceus': PlantProfile(
    commonName: 'Soft Brome',
    scientificName: 'Bromus hordeaceus',
    description: 'A cool-season, annual grass known for its soft texture and adaptability to various habitats.',
    growthHabits: 'Forms loose clumps with broad leaves and tall, open flower spikes.',
    ecologicalRoles: 'Often found in disturbed areas, provides forage for livestock, and contributes to soil health.',
    uses: 'Used in pastures, forage production, and soil stabilization.',
  ),
  'Festuca rubra': PlantProfile(
    commonName: 'Red Fescue',
    scientificName: 'Festuca rubra',
    description: 'A cool-season, perennial grass known for its fine texture and shade tolerance.',
    growthHabits: 'Forms dense, low-growing mats with fine, dark green leaves and small, greenish flower spikes.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is used in shaded areas.',
    uses: 'Popular in lawns, ground cover, and erosion control, especially in shaded areas.',
  ),
  'Deschampsia flexuosa': PlantProfile(
    commonName: 'Wavy Hairgrass',
    scientificName: 'Deschampsia flexuosa',
    description: 'A cool-season, perennial grass known for its delicate, airy flower heads and tolerance to poor soils.',
    growthHabits: 'Forms loose clumps with fine leaves and tall, slender flower spikes that create a delicate, airy appearance.',
    ecologicalRoles: 'Provides habitat for wildlife, supports soil health, and is used in naturalistic landscaping.',
    uses: 'Used in ornamental gardens, naturalistic landscaping, and as a ground cover in poor soils.',
  ),
  'Aristida basiramea': PlantProfile(
    commonName: 'Forked Threeawn',
    scientificName: 'Aristida basiramea',
    description: 'A warm-season, annual grass known for its unique, three-awned seed heads and adaptability to various habitats.',
    growthHabits: 'Forms loose clumps with narrow leaves and distinctive, three-awned seed heads.',
    ecologicalRoles: 'Provides ground cover in disturbed areas, supports soil health, and is adapted to a variety of habitats.',
    uses: 'Used in restoration projects, erosion control, and as a ground cover in disturbed areas.',
  ),
  'Bouteloua dactyloides': PlantProfile(
    commonName: 'Buffalograss',
    scientificName: 'Bouteloua dactyloides',
    description: 'A warm-season, perennial grass native to North America, known for its low growth habit and drought tolerance.',
    growthHabits: 'Forms dense, low-growing mats with fine leaves and small, inconspicuous flower spikes.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is drought-tolerant.',
    uses: 'Popular in low-maintenance lawns, ground cover, and as a turfgrass in arid regions.',
  ),
   'Chloris virgata': PlantProfile(
    commonName: 'Feathertop Rhodes Grass',
    scientificName: 'Chloris virgata',
    description: 'A warm-season, annual grass known for its distinctive, feathery seed heads and tolerance to dry conditions.',
    growthHabits: 'Forms loose clumps with narrow leaves and tall, feathery seed heads.',
    ecologicalRoles: 'Provides ground cover in disturbed areas and supports soil health.',
    uses: 'Used in erosion control, ground cover, and restoration projects in dry regions.',
  ),
  'Setaria viridis': PlantProfile(
    commonName: 'Green Foxtail',
    scientificName: 'Setaria viridis',
    description: 'A warm-season, annual grass known for its bristly seed heads and rapid growth.',
    growthHabits: 'Forms loose clumps with broad leaves and bristly, cylindrical seed heads.',
    ecologicalRoles: 'Often found in disturbed areas and provides food for wildlife.',
    uses: 'Used in forage production, cover cropping, and as a food source for wildlife.',
  ),
  'Echinochloa crus-galli': PlantProfile(
    commonName: 'Barnyardgrass',
    scientificName: 'Echinochloa crus-galli',
    description: 'A warm-season, annual grass known for its aggressive growth and adaptability to wet conditions.',
    growthHabits: 'Forms dense clumps with broad leaves and large, spreading flower heads.',
    ecologicalRoles: 'Provides cover in wet areas, supports soil health, and is a common weed in agricultural fields.',
    uses: 'Used in wetland restoration, forage production, and as a cover crop.',
  ),
  'Pennisetum purpureum': PlantProfile(
    commonName: 'Napier Grass',
    scientificName: 'Pennisetum purpureum',
    description: 'A warm-season, perennial grass known for its tall growth and high biomass production.',
    growthHabits: 'Forms dense clumps with tall, cane-like stems and large, plume-like flower heads.',
    ecologicalRoles: 'Provides forage for livestock, supports soil health, and is used in biomass production.',
    uses: 'Widely used in forage production, bioenergy, and erosion control.',
  ),
  'Cenchrus echinatus': PlantProfile(
    commonName: 'Southern Sandbur',
    scientificName: 'Cenchrus echinatus',
    description: 'A warm-season, annual grass known for its spiny seed burs and adaptability to sandy soils.',
    growthHabits: 'Forms loose clumps with narrow leaves and spiny, burr-like seed heads.',
    ecologicalRoles: 'Often found in disturbed sandy areas and provides ground cover.',
    uses: 'Used in erosion control and as a ground cover in sandy soils.',
  ),
  'Bothriochloa bladhii': PlantProfile(
    commonName: 'Forest Bluegrass',
    scientificName: 'Bothriochloa bladhii',
    description: 'A warm-season, perennial grass known for its adaptability to various soils and its bluish-green foliage.',
    growthHabits: 'Forms dense clumps with narrow, bluish-green leaves and feathery flower heads.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is used in pastures.',
    uses: 'Used in pasture management, forage production, and erosion control.',
  ),
  'Hyparrhenia rufa': PlantProfile(
    commonName: 'Jaragua Grass',
    scientificName: 'Hyparrhenia rufa',
    description: 'A warm-season, perennial grass known for its tall growth and use in tropical and subtropical regions.',
    growthHabits: 'Forms dense clumps with tall, slender stems and loose, feathery flower heads.',
    ecologicalRoles: 'Provides forage for livestock, supports soil health, and is used in tropical pastures.',
    uses: 'Widely used in tropical pasture management, forage production, and erosion control.',
  ),
  'Urochloa brizantha': PlantProfile(
    commonName: 'Palisade Grass',
    scientificName: 'Urochloa brizantha',
    description: 'A warm-season, perennial grass known for its high-quality forage and adaptability to tropical regions.',
    growthHabits: 'Forms dense clumps with broad leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides high-quality forage for livestock and supports soil health.',
    uses: 'Used in tropical pastures, forage production, and soil stabilization projects.',
  ),
  'Megathyrsus maximus': PlantProfile(
    commonName: 'Guinea Grass',
    scientificName: 'Megathyrsus maximus',
    description: 'A warm-season, perennial grass known for its robust growth and use in tropical and subtropical regions.',
    growthHabits: 'Forms dense clumps with tall, cane-like stems and large, plume-like flower heads.',
    ecologicalRoles: 'Provides forage for livestock, supports soil health, and is used in biomass production.',
    uses: 'Used in tropical pasture management, forage production, and bioenergy.',
  ),
  'Eragrostis curvula': PlantProfile(
    commonName: 'Weeping Lovegrass',
    scientificName: 'Eragrostis curvula',
    description: 'A warm-season, perennial grass known for its fine texture and adaptability to poor soils.',
    growthHabits: 'Forms loose clumps with fine, weeping leaves and small, airy flower heads.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is used in erosion control.',
    uses: 'Used in erosion control, ground cover, and as a forage crop in dry regions.',
  ),
  'Eriochloa procera': PlantProfile(
    commonName: 'Big Cupgrass',
    scientificName: 'Eriochloa procera',
    description: 'A warm-season, perennial grass known for its distinctive cup-shaped seed heads and adaptability to wet conditions.',
    growthHabits: 'Forms dense clumps with broad leaves and large, cup-shaped seed heads.',
    ecologicalRoles: 'Provides cover in wet areas, supports soil health, and is used in wetland restoration.',
    uses: 'Used in wetland restoration, forage production, and as a cover crop in wet conditions.',
  ),
  'Aegilops cylindrica': PlantProfile(
    commonName: 'Jointed Goatgrass',
    scientificName: 'Aegilops cylindrica',
    description: 'A cool-season, annual grass known for its jointed seed heads and adaptability to disturbed areas.',
    growthHabits: 'Forms loose clumps with narrow leaves and jointed, cylindrical seed heads.',
    ecologicalRoles: 'Often found in disturbed areas, provides food for wildlife, and can be a weed in agricultural fields.',
    uses: 'Used in soil stabilization and as a cover crop, but also managed as a weed in some regions.',
  ),
  'Aegilops triuncialis': PlantProfile(
    commonName: 'Barbed Goatgrass',
    scientificName: 'Aegilops triuncialis',
    description: 'A cool-season, annual grass known for its barbed seed heads and adaptability to dry, disturbed areas.',
    growthHabits: 'Forms loose clumps with narrow leaves and barbed, spiky seed heads.',
    ecologicalRoles: 'Often found in dry, disturbed areas, provides food for wildlife, and is a common weed in some regions.',
    uses: 'Used in soil stabilization and as a cover crop, but also managed as a weed in some regions.',
  ),
  'Aegilops tauschii': PlantProfile(
    commonName: 'Tausch\'s Goatgrass',
    scientificName: 'Aegilops tauschii',
    description: 'A cool-season, annual grass known for its role in wheat hybridization and adaptability to disturbed areas.',
    growthHabits: 'Forms loose clumps with narrow leaves and small, inconspicuous seed heads.',
    ecologicalRoles: 'Provides genetic material for wheat breeding and is found in disturbed areas.',
    uses: 'Used in wheat breeding programs and soil stabilization projects.',
  ),
  'Secale montanum': PlantProfile(
    commonName: 'Mountain Rye',
    scientificName: 'Secale montanum',
    description: 'A cool-season, perennial grass known for its hardiness and adaptability to high-altitude regions.',
    growthHabits: 'Forms dense clumps with narrow leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides forage for livestock, supports soil health, and is adapted to high-altitude regions.',
    uses: 'Used in forage production, soil stabilization, and as a cover crop in high-altitude regions.',
  ),
  'Triticum monococcum': PlantProfile(
    commonName: 'Einkorn Wheat',
    scientificName: 'Triticum monococcum',
    description: 'An ancient wheat species known for its hardiness and high nutritional value.',
    growthHabits: 'Forms dense clumps with narrow leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides food for humans and is used in traditional and organic farming systems.',
    uses: 'Used in baking, traditional farming, and as a source of ancient grains in specialty food products.',
  ),
  'Bromus tectorum': PlantProfile(
    commonName: 'Cheatgrass',
    scientificName: 'Bromus tectorum',
    description: 'A cool-season, annual grass known for its aggressive growth and adaptability to disturbed areas.',
    growthHabits: 'Forms loose clumps with narrow leaves and small, spike-like flower heads.',
    ecologicalRoles: 'Often found in disturbed areas, provides cover for wildlife, and is considered a weed in some regions.',
    uses: 'Managed as a weed in agricultural fields, but also used in soil stabilization and cover cropping.',
  ),
  'Elymus repens': PlantProfile(
    commonName: 'Quackgrass',
    scientificName: 'Elymus repens',
    description: 'A cool-season, perennial grass known for its aggressive growth and adaptability to various soils.',
    growthHabits: 'Forms dense clumps with broad leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Often found in disturbed areas, provides cover for wildlife, and is considered a weed in some regions.',
    uses: 'Managed as a weed in agricultural fields, but also used in soil stabilization and cover cropping.',
  ),
  'Agropyron cristatum': PlantProfile(
    commonName: 'Crested Wheatgrass',
    scientificName: 'Agropyron cristatum',
    description: 'A cool-season, perennial grass known for its hardiness and adaptability to dry conditions.',
    growthHabits: 'Forms dense clumps with narrow leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides forage for livestock, supports soil health, and is used in rangeland restoration.',
    uses: 'Used in forage production, rangeland restoration, and erosion control.',
  ),
  'Anthoxanthum odoratum': PlantProfile(
    commonName: 'Sweet Vernal Grass',
    scientificName: 'Anthoxanthum odoratum',
    description: 'A cool-season, perennial grass known for its sweet aroma and adaptability to various soils.',
    growthHabits: 'Forms loose clumps with narrow leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is used in pastures and hay production.',
    uses: 'Used in forage production, haymaking, and lawn management.',
  ),
  'Avena fatua': PlantProfile(
    commonName: 'Wild Oat',
    scientificName: 'Avena fatua',
    description: 'A cool-season, annual grass known for its aggressive growth and adaptability to disturbed areas.',
    growthHabits: 'Forms loose clumps with broad leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Often found in disturbed areas, provides cover for wildlife, and is considered a weed in some regions.',
    uses: 'Managed as a weed in agricultural fields, but also used in soil stabilization and cover cropping.',
  ),
  'Glyceria maxima': PlantProfile(
    commonName: 'Reed Sweet-grass',
    scientificName: 'Glyceria maxima',
    description: 'A cool-season, perennial grass known for its adaptability to wet soils and aquatic habitats.',
    growthHabits: 'Forms dense clumps with broad leaves and tall, spike-like flower heads.',
    ecologicalRoles: 'Provides cover for aquatic wildlife, supports soil health, and is used in wetland restoration.',
    uses: 'Used in wetland restoration, erosion control, and as forage for livestock.',
  ),
  'Nardus stricta': PlantProfile(
    commonName: 'Mat-grass',
    scientificName: 'Nardus stricta',
    description: 'A cool-season, perennial grass known for its dense, mat-forming growth and adaptability to poor soils.',
    growthHabits: 'Forms dense mats with narrow leaves and small, spike-like flower heads.',
    ecologicalRoles: 'Provides ground cover, supports soil health, and is used in pasture management.',
    uses: 'Used in pasture management, erosion control, and as ornamental grass.',
  ),
 
  // Continue with the remaining plants in batches
};
